name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display the text file
        run: cat message.txt

      - name: Check file contains expected text
        run: grep "Hello from CI/CD lab" message.txt